server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  profiles:
    active:
      - dev
  liquibase:
    enabled: false

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: false

logging:
  level:
    root: INFO

